version: '3.8'
services:
  webapi:
    build:
      context: ./API/
    restart: unless-stopped
    entrypoint:
      - "./dev-entrypoint.sh"
    ports:
      - "52200"
    environment:
      PORT: 52200
      http_proxy: http://10.0.0.1:80
      APP_TIMEZONE: Europe/Paris
    volumes:
      - ./API:/var/www
    labels:
      - traefik.enable=true
      - traefik.http.routers.webchartapi.rule=PathPrefix(`/charteapi`)
      - traefik.http.routers.webchartapi.middlewares=strip-webchartapi-prefix
      - traefik.http.middlewares.strip-webchartapi-prefix.stripprefix.prefixes=/charteapi
      - traefik.http.routers.webchartapi.entrypoints=web
    depends_on:
      - database
    networks:
      vpcbr:
        ipv4_address: 172.23.0.4
  web:
    build:
      context: ./FRONT/
    restart: unless-stopped
    depends_on:
      - webapi
    environment:
      PORT: 80
      http_proxy: http://10.0.0.1:80
      APP_TIMEZONE: Europe/Paris
    volumes:
      - ./FRONT:/usr/local/apache2/htdocs/
    labels:
      - traefik.enable=true
      - traefik.http.routers.webchart.rule=PathPrefix(`/charte`)
      - traefik.http.routers.webchart.middlewares=strip-webchart-prefix
      - traefik.http.middlewares.strip-webchart-prefix.stripprefix.prefixes=/charte
      - traefik.http.routers.webchart.entrypoints=web
    networks:
      vpcbr:
        ipv4_address: 172.23.0.5